# Generated by Django 2.1.2 on 2019-04-08 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banks',
            fields=[
                ('bankID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('bankName', models.CharField(max_length=50, unique=True)),
                ('bankLocation', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LCat',
            fields=[
                ('lcatID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('lcatDesc', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('lineID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('lineDT', models.DateTimeField(verbose_name='Transaction Date')),
                ('lineAmount', models.FloatField()),
                ('lineShort', models.CharField(max_length=50)),
                ('lineLong', models.TextField(blank=True, null=True)),
                ('lineBalance', models.FloatField()),
                ('lineBank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finances.Banks')),
                ('lineCategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finances.LCat')),
            ],
        ),
    ]
