# Generated by Django 2.1.2 on 2019-04-08 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('itemID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('itemName', models.CharField(max_length=200)),
                ('itemDescription', models.CharField(max_length=400)),
                ('itemQuantity', models.CharField(max_length=200)),
                ('itemAdded', models.DateTimeField(verbose_name='Date Added')),
                ('itemPurchased', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('storeID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('storeName', models.CharField(max_length=200)),
                ('storeLocation', models.CharField(max_length=200)),
                ('storeStreet', models.CharField(blank=True, max_length=200, null=True)),
                ('storeCity', models.CharField(blank=True, max_length=200, null=True)),
                ('storeState', models.CharField(blank=True, max_length=200, null=True)),
                ('storeZip', models.CharField(blank=True, max_length=11, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='itemStore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.Store'),
        ),
    ]
